from enum import Enum

ARG_KINDS = Enum( 'ARG_KINDS', 'ARG_POS ARG_OPT ARG_STAR ARG_NAMED ARG_STAR2')
# ARG_POS: positional
# ARG_OPT: optional argument (functions only, not calls)
# ARG_STAR: *arg argument
# ARG_NAMED: keyword argument x=y in call, or keyword-only function arg
# ARG_STAR2 **arg argument

inproduct = {'type': {'is_classmethod_class': False, 'name': '"inproduct"', 'arg_names': ['v', 'arg2'], 'arg_kinds': [0, 0], 'variables': [], 'ret_type': {'.class': 'Instance', 'type_ref': 'builtins.list', 'args': [{'.class': 'TypeType', 'item': {'.class': 'Instance', 'type_ref': 'foo.Foo'}}]}, '.class': 'CallableType', 'implicit': False, 'arg_types': [{'.class': 'Instance', 'type_ref': 'builtins.list', 'args': [{'.class': 'TupleType', 'fallback': {'.class': 'Instance', 'type_ref': 'builtins.tuple', 'args': [{'.class': 'AnyType'}]}, 'implicit': False, 'items': [{'.class': 'Instance', 'type_ref': 'builtins.float'}, {'.class': 'Instance', 'type_ref': 'builtins.float'}]}]}, {'.class': 'Instance', 'type_ref': 'builtins.str'}], 'is_ellipsis_args': False, 'fallback': {'.class': 'Instance', 'type_ref': 'builtins.function'}}, 'name': 'inproduct', 'arg_names': ['v', 'arg2'], 'arg_kinds': [0, 0], '.class': 'FuncDef', 'flags': [], 'fullname': 'test_def.inproduct'}
builtins_only = {'type': {'is_classmethod_class': False, 'name': '"builtins_only"', 'arg_names': ['arg2', 'arg3'], 'arg_kinds': [0, 0], 'variables': [], 'ret_type': {'.class': 'Instance', 'type_ref': 'builtins.complex'}, '.class': 'CallableType', 'implicit': False, 'arg_types': [{'.class': 'Instance', 'type_ref': 'builtins.float'}, {'.class': 'Instance', 'type_ref': 'builtins.int'}], 'is_ellipsis_args': False, 'fallback': {'.class': 'Instance', 'type_ref': 'builtins.function'}}, 'name': 'builtins_only', 'arg_names': ['arg2', 'arg3'], 'arg_kinds': [0, 0], '.class': 'FuncDef', 'flags': [], 'fullname': 'test_def.builtins_only'}
max_np_array = {'type': {'is_classmethod_class': False, 'name': '"max_np_array"', 'arg_names': ['arg1'], 'arg_kinds': [0], 'variables': [], 'ret_type': {'.class': 'Instance', 'type_ref': 'builtins.float'}, '.class': 'CallableType', 'implicit': False, 'arg_types': [{'.class': 'TypeType', 'item': {'.class': 'Instance', 'type_ref': 'numpy.ndarray', 'args': [{'.class': 'Instance', 'type_ref': 'builtins.float'}]}}], 'is_ellipsis_args': False, 'fallback': {'.class': 'Instance', 'type_ref': 'builtins.function'}}, 'name': 'max_np_array', 'arg_names': ['arg1'], 'arg_kinds': [0], '.class': 'FuncDef', 'flags': [], 'fullname': 'test_def.max_np_array'}
void_method = {'type': {'is_classmethod_class': False, 'name': '"void_method"', 'arg_names': ['arg'], 'arg_kinds': [0], 'variables': [], 'ret_type': {'.class': 'AnyType'}, '.class': 'CallableType', 'implicit': False, 'arg_types': [{'.class': 'Instance', 'type_ref': 'builtins.str'}], 'is_ellipsis_args': False, 'fallback': {'.class': 'Instance', 'type_ref': 'builtins.function'}}, 'name': 'void_method', 'arg_names': ['arg'], 'arg_kinds': [0], '.class': 'FuncDef', 'flags': [], 'fullname': 'test_def.void_method'}
void_no_args = {'type': None, 'name': 'void_no_args', 'arg_names': [], 'arg_kinds': [], '.class': 'FuncDef', 'flags': [], 'fullname': 'test_def.void_no_args'}
void_starargs = {'type': None, 'name': 'starargs', 'arg_names': ['args'], 'arg_kinds': [2], '.class': 'FuncDef', 'flags': [], 'fullname': 'test_def.starargs'}
void_starkwargs = {'type': None, 'name': 'starkwargs', 'arg_names': ['kwargs'], 'arg_kinds': [4], '.class': 'FuncDef', 'flags': [], 'fullname': 'test_def.starkwargs'}
